apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fmkzqd1cs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fmkzqd1cs-python 
  name: fmkzqd1cs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fmkzqd1cs-python 
